'use client'
import { useCallback, useEffect, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { supabase } from '@/lib/supabase'
import { koreaToday } from '@/lib/booking-time'
type Form = { name:string;address:string;public_phone:string;refund_policy:string;contact_email:string;business_number:string;notes:string;mou_signed_on:string;expires_on:string;registration_checked:boolean;insurance_checked:boolean;status:string }
type Academy = Form & {id:string}
type Instructor = {id:string;name:string;area:string;academy_id:string|null}
type Report = {id:string;name:string;total:number;requested:number;confirmed:number;completed:number;cancelled:number;completed_amount:number}
const empty:Form={name:'',address:'',public_phone:'',refund_policy:'',contact_email:'',business_number:'',notes:'',mou_signed_on:'',expires_on:'',registration_checked:false,insurance_checked:false,status:'draft'}
const statuses:Record<string,string>={draft:'준비 중',active:'운영 중',paused:'운영 중지'}
export default function AcademiesPage(){
 const router=useRouter();const[allowed,setAllowed]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const[academies,setAcademies]=useState<Academy[]>([]),[instructors,setInstructors]=useState<Instructor[]>([]),[links,setLinks]=useState<Record<string,string>>({}),[form,setForm]=useState<Form>({...empty}),[editing,setEditing]=useState<string|null>(null)
 const[month,setMonth]=useState(()=>koreaToday().slice(0,7)),[reportMonth,setReportMonth]=useState(''),[report,setReport]=useState<Report[]>([])
 const load=useCallback(async()=>{setLoading(true);try{const{data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login?next=%2Fadmin%2Facademies');return}const{data,error}=await supabase.rpc('admin_academy_overview');if(error)throw error;setAllowed(true);setAcademies(data.academies??[]);setInstructors(data.instructors??[]);setLinks({})}catch{setAllowed(false);setAcademies([]);setInstructors([]);setReport([]);setError('관리자 권한 또는 학원 목록을 확인하지 못했습니다. 다시 시도해주세요.')}finally{setLoading(false)}},[router])
 useEffect(()=>{void load()},[load])
 function edit(a:Academy){setEditing(a.id);setForm({...empty,...a,mou_signed_on:a.mou_signed_on||'',expires_on:a.expires_on||''});setNotice('');document.getElementById('academy-form')?.scrollIntoView({behavior:'smooth'})}
 async function save(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');setNotice('');try{const{error}=await supabase.rpc('admin_save_academy',{academy_data:form,target_academy_id:editing});if(error){setError(error.message.includes('ACADEMY_CHECKS_REQUIRED')?'운영 시작 전 MOU 체결일, 사업자번호, 주소·전화, 취소·환불 안내와 등록·보험 확인을 완료해주세요. 계약 기간도 확인해주세요.':'학원 저장에 실패했습니다. 입력 내용과 날짜를 확인해주세요.');return}setForm({...empty});setEditing(null);setNotice('제휴 학원을 저장했습니다.');await load()}catch{setError('저장 결과를 확인하지 못했습니다. 목록을 새로고침해주세요.')}finally{setBusy(false)}}
 async function assign(i:Instructor){setBusy(true);setError('');setNotice('');try{const{error}=await supabase.rpc('admin_assign_academy',{target_instructor_id:i.id,target_academy_id:links[i.id]||null});if(error)throw error;setNotice('교관의 학원 연결을 저장했습니다.');await load()}catch{setError('학원 연결 결과를 확인하지 못했습니다. 목록을 새로고침해주세요.')}finally{setBusy(false)}}
 async function monthly(){if(!month||busy)return;setBusy(true);setError('');setReport([]);setReportMonth('');try{const{data,error}=await supabase.rpc('admin_academy_monthly',{p_month:month+'-01'});if(error)throw error;setReport(data??[]);setReportMonth(month)}catch{setError('월간 실적을 불러오지 못했습니다. 다시 조회해주세요.')}finally{setBusy(false)}}
 return <main className="container section pageTop partnerAdmin"><div className="pageTitle"><span>YA TA PARTNERS</span><h1>제휴 학원 관리</h1><p>실차 연수 제휴 학원을 등록하고 소속 교관과 운영 실적을 관리합니다.</p></div><nav className="dashboardShortcuts" aria-label="제휴 관리 메뉴"><Link href="/admin/bookings">예약 운영 관리</Link><Link href="/admin/instructors">교관 승인 관리</Link><button className="ghostBtn" disabled={busy||loading} onClick={()=>{setError('');void load()}}>목록 새로고침</button></nav>
 {error&&<p role="alert" className="bookingError">{error}</p>}<p role="status">{notice}</p>{loading?<p>제휴 학원을 확인하는 중...</p>:allowed&&<>
 <section className="panel"><h2>첫 제휴 운영 순서</h2><ol><li>MOU에 수업 제공·결제·취소·고객 안내 담당과 수수료 조건을 정합니다.</li><li>실제 자료를 확인하고 아래 학원 정보를 등록합니다.</li><li>학원을 운영 중으로 전환하고 소속 교관을 연결합니다.</li><li>교관이 가능 시간을 열고 첫 예약을 함께 점검합니다.</li><li>월간 실적을 대조한 뒤 계약 조건에 따라 별도로 정산합니다.</li></ol><p>현재 결제는 학원 직접 결제이며 자동 알림·수수료 정산·학원 전용 계정은 제공하지 않습니다. 실내 시뮬레이터 상품은 이 실차 연수 예약과 별도로 협의해주세요.</p></section>
 <form id="academy-form" className="panel academyForm" onSubmit={save}><h2>{editing?'학원 정보 수정':'제휴 학원 등록'}</h2><fieldset disabled={busy}><div className="academyFields">{([['name','학원명'],['address','학원 주소'],['public_phone','고객용 전화번호'],['business_number','사업자등록번호'],['contact_email','운영 담당자 이메일']] as const).map(([key,label])=><label key={key}>{label}<input required={key==='name'} type={key==='contact_email'?'email':'text'} maxLength={key==='name'?120:key==='business_number'?30:key==='public_phone'?50:key==='address'?500:200} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label>MOU 체결일<input type="date" value={form.mou_signed_on} onChange={e=>setForm({...form,mou_signed_on:e.target.value})}/></label><label>계약 종료일 · 선택<input type="date" value={form.expires_on} min={form.mou_signed_on||undefined} onChange={e=>setForm({...form,expires_on:e.target.value})}/></label><label>운영 상태<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{Object.entries(statuses).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div><label>고객에게 보여줄 취소·환불 안내<textarea maxLength={4000} value={form.refund_policy} onChange={e=>setForm({...form,refund_policy:e.target.value})}/></label><label>운영 메모 · 관리자만 확인<textarea maxLength={4000} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><label className="academyCheck"><input type="checkbox" checked={form.registration_checked} onChange={e=>setForm({...form,registration_checked:e.target.checked})}/>학원 등록·교육 제공 자격 자료 확인</label><label className="academyCheck"><input type="checkbox" checked={form.insurance_checked} onChange={e=>setForm({...form,insurance_checked:e.target.checked})}/>해당 연수의 차량·보험 적용 자료 확인</label><p>확인 항목은 실제 자료를 검토한 뒤 선택하세요. 교관별 보험·차량 확인은 교관 승인 관리에서 별도로 진행합니다.</p><div className="dashboardShortcuts"><button className="primaryBtn" type="submit">{busy?'저장 중...':'학원 저장'}</button>{editing&&<button className="ghostBtn" type="button" onClick={()=>{setEditing(null);setForm({...empty})}}>새 학원 입력</button>}</div></fieldset></form>
 <section className="panel"><h2>등록 학원 · {academies.length}곳</h2>{!academies.length&&<p>아직 등록한 제휴 학원이 없습니다.</p>}{academies.map(a=><article className="academyRow" key={a.id}><div><strong>{a.name}</strong><p>{statuses[a.status]} · 교관 {instructors.filter(i=>i.academy_id===a.id).length}명</p><small>{a.expires_on?`계약 종료 ${a.expires_on}`:'계약 종료일 미입력'}</small></div><button className="ghostBtn" disabled={busy} onClick={()=>edit(a)}>학원 정보 수정</button></article>)}</section>
 <section className="panel"><h2>소속 교관 연결</h2><p>준비 중·운영 중지 학원에 연결된 교관은 새 예약을 받을 수 없습니다. 기존 예약의 학원 정보는 바뀌지 않습니다.</p>{instructors.map(i=><div className="academyRow" key={i.id}><div><strong>{i.name}</strong><p>{i.area}</p></div><label>{i.name} 소속 학원<select disabled={busy} value={links[i.id]??i.academy_id??''} onChange={e=>setLinks({...links,[i.id]:e.target.value})}><option value="">미연결</option>{academies.map(a=><option key={a.id} value={a.id}>{a.name} · {statuses[a.status]}</option>)}</select></label><button className="ghostBtn" disabled={busy||links[i.id]===undefined} onClick={()=>void assign(i)}>연결 저장</button></div>)}</section>
 <section className="panel"><h2>학원별 월간 실적</h2><p>수업 예정일 기준 집계입니다. 완료 수업 예약금액은 실제 결제액·정산액과 다를 수 있습니다. 기존 학원 미연결 예약은 포함하지 않습니다.</p><div className="dashboardShortcuts"><label>조회 월<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><button className="ghostBtn" disabled={busy||!month} onClick={()=>void monthly()}>월간 실적 조회</button></div>{reportMonth&&<><h3>{reportMonth} 실적</h3>{!report.length?<p>등록된 제휴 학원이 없습니다.</p>:<div className="academyTable"><table><thead><tr><th>학원</th><th>전체</th><th>요청</th><th>확정</th><th>완료</th><th>취소</th><th>완료 수업 예약금액</th></tr></thead><tbody>{report.map(r=><tr key={r.id}><th>{r.name}</th><td>{r.total}</td><td>{r.requested}</td><td>{r.confirmed}</td><td>{r.completed}</td><td>{r.cancelled}</td><td>{Number(r.completed_amount).toLocaleString()}원</td></tr>)}</tbody></table></div>}</>}</section>
 </> }</main>
}
